version: '3'
services:
  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration
    volumes:
     - ./sql:/flyway/sql
     - ./bin:/flyway/bin
    entrypoint: ["bash", "/flyway/bin/wait-for-it.sh", "--timeout=30", "db:1433", "--", "flyway"]      
    command: -url=jdbc:sqlserver://db;database=master -user=sa -password=1234qwerASDF -mixed=true migrate
    depends_on:
      - db
  db:
    image: mssql-rhel
    environment:
      SA_PASSWORD: "1234qwerASDF"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1557:1433"